apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: github-actions  # optional: set if you're using a specific namespace
spec:
  containers:
    - name: my-container
      image: nginx:latest
      ports:
        - containerPort: 80
